version: '3.9'

services:
  backend:
    build:
      context: ./App.API
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./App.Web
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
